### ISSUE TITLE
Refactor texture caching to share Sources between Textures

### ISSUE THREAD

**Issue by mrxz** [aframevr/aframe#5449]
**Description:**
A-Frame currently caches Textures in order to prevent duplicate uploads. The cache takes both the source (e.g. url) and some texture properties into account. However it fails to correctly handle cases where these properties change after the fact. See #5441, #1372, #5120.

I started on refactoring parts of the texture handling to cache [`Source`](https://threejs.org/docs/index.html?q=Source#api/en/textures/Source) instead. Three.js can gracefully handle only uploading textures as needed when sharing one Source between multiple `Texture` instances. The changeset for this is becoming quite large, so it's probably best to split it up in several smaller PRs. What doesn't help is that there are places that sidestep the centralized texture handling, so I'll try to unify code-paths first.

This issue is to track progress:

- [x] Finally remove `sphericalEnvMap` as it's broken/incorrect for >3 years (https://github.com/aframevr/aframe/pull/4747, deprecation in #5454 )
- [x] Remove iOS 10 specific HLS workaround, as it now causes new issues (https://github.com/aframevr/aframe/issues/4134, https://github.com/aframevr/aframe/pull/5450)
- [x] Unify `updateMapMaterialFromData`, `updateMap` and `updateDistortionMap` (#5453)
- [x] Unify `envMap` loading in both `phong.js` and `standard.js` and let it re-use texture cache (#5454 )
- [ ] Cache `Source` instead of `Textures` (#5455 )

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5455
